

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8' 
    addToPath: true 

- script: pip install pandas pyyaml
  displayName: 'Install dependencies'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'starcounter.py'
    #arguments: # Optional
    #pythonInterpreter: # Optional
    #workingDirectory: # Optional
    #failOnStderr: false # Optional