

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8' 
    addToPath: true 

- script: pip install pandas pyyaml
  displayName: 'Install dependencies'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: 'starcounter.py'
    #arguments: # Optional
    #pythonInterpreter: # Optional
    #workingDirectory: # Optional
    #failOnStderr: false # Optional

- script: cat STARS.md
  displayName: 'Display Readme'

- publish: $(System.DefaultWorkingDirectory)/STARS.md
  artifact: STARS

- script: |
    git config --global user.email "info@zephyrtransport.org"
    git config --global user.name "Zephyr Transport"
    git add STARS.md
    git commit -m "Update stars [skip ci]"
    git push origin azure-pipelines
  displayName: 'Git Push'
